### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by JacksonEpworth** [raveberry/raveberry#103]
Today I did a fresh install of Raveberry, when I tried to access the front page I came across the following:
"500 Internal Server Error
Exception inside application.

Daphne"

**Comment by raveberry** [comment]
That shouldn't happen. Whats the output of `journalctl -xefu daphne`? Is there anything related in `/var/log/syslog` or `/opt/raveberry/logs/error.log`?
Does the issue persist after `sudo systemctl restart daphne`?

**Comment by JacksonEpworth** [comment]
`2021-04-06 15:53:11 server.application_checker:288 ERROR  Exception inside application: async_to_sync can only be applied to async functions.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/channels/http.py", line 200, in __call__
    self.send = async_to_sync(send)
  File "/usr/local/lib/python3.7/dist-packages/asgiref/sync.py", line 105, in __init__
    raise TypeError("async_to_sync can only be applied to async functions.")
TypeError: async_to_sync can only be applied to async functions.
2021-04-06 15:53:12 server.application_checker:288 ERROR  Exception inside application: async_to_sync can only be applied to async functions.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/channels/http.py", line 200, in __call__
    self.send = async_to_sync(send)
  File "/usr/local/lib/python3.7/dist-packages/asgiref/sync.py", line 105, in __init__
    raise TypeError("async_to_sync can only be applied to async functions.")
TypeError: async_to_sync can only be applied to async functions.
2021-04-06 15:54:44 server.application_checker:288 ERROR  Exception inside application: async_to_sync can only be applied to async functions.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/channels/http.py", line 200, in __call__
    self.send = async_to_sync(send)
  File "/usr/local/lib/python3.7/dist-packages/asgiref/sync.py", line 105, in __init__
    raise TypeError("async_to_sync can only be applied to async functions.")
TypeError: async_to_sync can only be applied to async functions.
2021-04-06 15:54:45 server.application_checker:288 ERROR  Exception inside application: async_to_sync can only be applied to async functions.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/channels/http.py", line 200, in __call__
    self.send = async_to_sync(send)
  File "/usr/local/lib/python3.7/dist-packages/asgiref/sync.py", line 105, in __init__
    raise TypeError("async_to_sync can only be applied to async functions.")
TypeError: async_to_sync can only be applied to async functions.
2021-04-06 16:11:26 server.application_checker:288 ERROR  Exception inside application: async_to_sync can only be applied to async functions.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/channels/http.py", line 200, in __call__
    self.send = async_to_sync(send)
  File "/usr/local/lib/python3.7/dist-packages/asgiref/sync.py", line 105, in __init__
    raise TypeError("async_to_sync can only be applied to async functions.")
TypeError: async_to_sync can only be applied to async functions.
2021-04-06 16:11:27 server.application_checker:288 ERROR  Exception inside application: async_to_sync can only be applied to async functions.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/channels/http.py", line 200, in __call__
    self.send = async_to_sync(send)
  File "/usr/local/lib/python3.7/dist-packages/asgiref/sync.py", line 105, in __init__
    raise TypeError("async_to_sync can only be applied to async functions.")
TypeError: async_to_sync can only be applied to async functions.
2021-04-06 16:14:01 server.application_checker:288 ERROR  Exception inside application: async_to_sync can only be applied to async functions.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/channels/http.py", line 200, in __call__
    self.send = async_to_sync(send)
  File "/usr/local/lib/python3.7/dist-packages/asgiref/sync.py", line 105, in __init__
    raise TypeError("async_to_sync can only be applied to async functions.")
TypeError: async_to_sync can only be applied to async functions.
2021-04-06 16:14:02 server.application_checker:288 ERROR  Exception inside application: async_to_sync can only be applied to async functions.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/channels/http.py", line 200, in __call__
    self.send = async_to_sync(send)
  File "/usr/local/lib/python3.7/dist-packages/asgiref/sync.py", line 105, in __init__
    raise TypeError("async_to_sync can only be applied to async functions.")
TypeError: async_to_sync can only be applied to async functions.
`

**Comment by raveberry** [comment]
Apparently you've discovered an issue with the newest version of `asgiref`: https://github.com/django/asgiref/issues/251
I will patch the code or pin the dependency depending on the outcome. Until then, you can downgrade with
`sudo pip3 install asgiref==3.3.1`.
After a restart of `daphne` you should be good to go.

**Comment by JacksonEpworth** [comment]
Sweet, it worked. Thank you very much

**Comment by raveberry** [comment]
Great, have fun!
Thanks for the quick responses.

**Comment by raveberry** [comment]
asgiref 3.3.4 (released yesterday) fixes this problem, so new installs are unaffected from now on.
