### ISSUE TITLE
500 Internal Server Error after manual install on Pi4

### ISSUE THREAD

**Issue by copykatze** [raveberry/raveberry#59]
Hey, very nice project, thanks for sharing! 

Unfortunatelly I am struggeling a bit with the installation, although it seems pretty straight froward.

I followed the manual install instructions on a Pi 1 4 with a fresh Raspberry Pi OS (32-bit) Lite Minimal image based on Debian Buster (Version: May 2020, Release date: 2020-05-27, Kernel version: 4.19), no problems during installation. 

```
***** Configuring Webserver *****
nginx...
daphne...
gunicorn...

***** Finished *****

Raveberry was installed on this system!
You can now visit http://raveberry/
A reboot might be necessary for all features to be active.
```

After finishing, I did the recommended restart.

I can reach the server, but it only shows
```
500 Internal Server Error
Exception inside application.
Daphne
```

I checked all the suggested status and logs from the debugging section, but it all seems to be up and running without errors. Are there any other suggestions where I could look for problems?

Thanks and best regards,
CC

**Comment by raveberry** [comment]
That should definitely not happen, especially on a fresh Raspbian install.

Just to make it clear, `/opt/raveberry/logs/error.log` shows no related errors?
This means we need to poke around for the cause.

One possibility could be that the database was not successfully migrated. Is postgres running (`systemctl status postgresql`)?
Does the raveberry database exist?
```
$ sudo -u postgres psql
postgres=# \list
postgres=# \connect raveberry
postgres=# \dt
```
`\list` should contain raveberry as a database and `\dt` should show about 30 entries.

**Comment by copykatze** [comment]
Oh no, I suppose I looked at the wrong logs (/var/log/syslog and /var/log/nginx/*).
There is a lot going on in /opt/raveberry/logs
Sorry for missing this on the debugging page, no idea how I could miss it :(
Thanks for the very quick help, I will try to find the problem in the log now.

**Comment by raveberry** [comment]
Looking at the debug.md myself I see that it is a little outdated, I should update it.
I'd be happy to know about the reason for the error so I can fix it (or at least provide better error messages).

**Comment by copykatze** [comment]
Ok, the content seems to be the same error over and over again, but I don't understand its meaning or cause or what I did wrong during installation.

This is the error:

```
2020-07-02 14:32:48 server.application_checker:288 ERROR  Exception inside application: relation "core_setting" does not exist
LINE 1: ..."core_setting"."key", "core_setting"."value" FROM "core_sett...
                                                             ^
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "core_setting" does not exist
LINE 1: ..."core_setting"."key", "core_setting"."value" FROM "core_sett...
                                                             ^
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 100, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python3.7/dist-packages/django/urls/resolvers.py", line 536, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.7/dist-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.7/dist-packages/django/urls/resolvers.py", line 584, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.7/dist-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.7/dist-packages/django/urls/resolvers.py", line 577, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./main/urls.py", line 23, in <module>
    url(r"\/?", include("core.urls")),
  File "/usr/local/lib/python3.7/dist-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./core/urls.py", line 14, in <module>
    BASE = Base()
  File "./core/base.py", line 29, in __init__
    self.settings = Settings(self)
  File "./core/settings/settings.py", line 80, in __init__
    self.basic = Basic(base)
  File "./core/settings/basic.py", line 23, in __init__
    self.voting_system = Settings.get_setting("voting_system", "False") == "True"
  File "./core/settings/settings.py", line 48, in get_setting
    return Setting.objects.get_or_create(key=key, defaults={"value": default})[
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 538, in get_or_create
    return self.get(**kwargs), False
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/sql/compiler.py", line 1140, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)

django.db.utils.ProgrammingError: relation "core_setting" does not exist
LINE 1: ..."core_setting"."key", "core_setting"."value" FROM "core_sett...
```

Should I just try a fresh install? I wouldn't mind, but I also would not mind trying to understand what went wrong, but I am afraid this is above my skills :-)

**Comment by copykatze** [comment]
And there seems to be something wrong with the database:

```
pi@raveberry:~ $ systemctl status postgresql
● postgresql.service - PostgreSQL RDBMS
   Loaded: loaded (/lib/systemd/system/postgresql.service; enabled; vendor preset: enabled)
   Active: active (exited) since Thu 2020-07-02 13:17:14 BST; 49min ago
 Main PID: 763 (code=exited, status=0/SUCCESS)
    Tasks: 0 (limit: 4035)
   Memory: 0B
   CGroup: /system.slice/postgresql.service

Jul 02 13:17:14 raveberry systemd[1]: Starting PostgreSQL RDBMS...
Jul 02 13:17:14 raveberry systemd[1]: Started PostgreSQL RDBMS.
pi@raveberry:~ $ sudo -u postgres psql
psql (11.7 (Raspbian 11.7-0+deb10u1))
Type "help" for help.

postgres=# \list
                                  List of databases
   Name    |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges
-----------+----------+----------+-------------+-------------+-----------------------
 postgres  | postgres | UTF8     | en_GB.UTF-8 | en_GB.UTF-8 |
 raveberry | postgres | UTF8     | en_GB.UTF-8 | en_GB.UTF-8 |
 template0 | postgres | UTF8     | en_GB.UTF-8 | en_GB.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_GB.UTF-8 | en_GB.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
(4 rows)

postgres=# \connect raveberry
You are now connected to database "raveberry" as user "postgres".
raveberry=# \dt
Did not find any relations.
```

**Comment by raveberry** [comment]
This looks like the database was not migrated during install.
Could you go into `/opt/raveberry` and run `sudo -Hu www-data DJANGO_MOCK=1 FORCE_POSTGRES=1 python3 manage.py migrate`?
This is the command that is called during the installation to migrate the database.

**Comment by raveberry** [comment]
oh, I found the error...

**Comment by copykatze** [comment]
Sure, I even remember to see that output during installation.

```
pi@raveberry:/opt/raveberry $ sudo -Hu www-data DJANGO_MOCK=1 FORCE_POSTGRES=1 python3 manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, core, sessions, watson
Running migrations:
  No migrations to apply.
```

**Comment by copykatze** [comment]
> oh, I found the error...

I' excited what it is... and I hope it was not something really stupid of me...

I have to get off the computer now, but I am excited to continue on this as soon as I can :-)

**Comment by raveberry** [comment]
I just pushed the bugfix. Just run `pip3 install -U raveberry` and then do the system install again and you should be fine.

It was a stupid error, but completely on my side.
The problem was that I recently changed how the database is selected during startup. There is the debug database (sqlite) and the production database (postgres). I added a `DJANGO_POSTGRES` environment that alwas selects the postgres database, even when `DJANGO_MOCK` is active (which usually uses the debug database). Internally I refer to the postgres override as `FORCE_POSTGRES`. Unfortunately, I used `FORCE_POSTGRES` in the install script, which then did not do anything.
I even tested it, but obviously not enough. The switch did not work, so the debug database was used. It looked like it worked, but the migration was performed on the wrong database.

**Comment by copykatze** [comment]
Yeees that worked! Thanks for the quick help! And I'm glad I did not wast your time because I missed a step :) can't wait to use it, but that must wait for now...

**Comment by raveberry** [comment]
Thanks a lot for raising the issue. And have fun with it later!

**Comment by copykatze** [comment]
Hi, I hate to bother you again... it seems to work fine now (I am listening to music) but I can't login to the admin section as my admin password is refused. Maybe this is because the wrong DB was connected at the time when I set the admin password during installation?

I checked the DB for users and to me it looks like there are none:
```
raveberry=# SELECT * FROM auth_user;
 id | password | last_login | is_superuser | username | first_name | last_name | email | is_staff | is_active | date_joined
----+----------+------------+--------------+----------+------------+-----------+-------+----------+-----------+-------------
(0 rows)
```
Could I just create a new entry for a user here? I suppose I would need to run migrations afterwards? And is a auth_group relation mandatory, so I would need to create one as well?
```
raveberry=# SELECT * FROM auth_group;
 id | name
----+------
(0 rows)
```
If this isn't a trivial fix, it would not be a problem for me just to start again. I'm just curious to understand and fix things if I can :)

**Comment by raveberry** [comment]
You are not bothering at all. As long as you encounter problems, please report them. After all, others might have them as well.

You are right, the first install created users for the wrong database. The second time, no users where created, as the database already existed (and thus user creation was skipped).
This is the relevant command from `database.sh`:
```
sudo -Hu www-data DJANGO_MOCK=1 DJANGO_POSTGRES=1 python3 manage.py shell <<-EOF
	from django.contrib.auth.models import User
	User.objects.create_superuser('admin', email='', password='$ADMIN_PASSWORD')
	User.objects.create_user('mod', password='mod')
EOF
```
Replace `$ADMIN_PASSWORD` with your password of choice and run this in `/opt/raveberry`, then you are good to go.

**Comment by copykatze** [comment]
Thanks again, that worked :-)
