### ISSUE TITLE
ModuleNotFoundError: No module named 'sass'

### ISSUE THREAD

**Issue by MickyGX** [raveberry/raveberry#60]
So I've been using Raveberry for a while now without issue. I recently upgraded my NAS and reinstalled it from scratch. When I try and goto to raveberry I get '502 Bad Gateway'. Looking in the logs it looks like its trying to load a module called sass without luck.

```
daphne_1      | Operations to perform:
daphne_1      |   Apply all migrations: admin, auth, contenttypes, core, sessions, watson
daphne_1      | Running migrations:
daphne_1      |   Applying contenttypes.0001_initial... OK
daphne_1      |   Applying auth.0001_initial... OK
daphne_1      |   Applying admin.0001_initial... OK
daphne_1      |   Applying admin.0002_logentry_remove_auto_add... OK
daphne_1      |   Applying admin.0003_logentry_add_action_flag_choices... OK
daphne_1      |   Applying contenttypes.0002_remove_content_type_name... OK
daphne_1      |   Applying auth.0002_alter_permission_name_max_length... OK
daphne_1      |   Applying auth.0003_alter_user_email_max_length... OK
daphne_1      |   Applying auth.0004_alter_user_username_opts... OK
daphne_1      |   Applying auth.0005_alter_user_last_login_null... OK
daphne_1      |   Applying auth.0006_require_contenttypes_0002... OK
daphne_1      |   Applying auth.0007_alter_validators_add_error_messages... OK
daphne_1      |   Applying auth.0008_alter_user_username_max_length... OK
daphne_1      |   Applying auth.0009_alter_user_last_name_max_length... OK
daphne_1      |   Applying auth.0010_alter_group_name_max_length... OK
daphne_1      |   Applying auth.0011_update_proxy_permissions... OK
daphne_1      |   Applying core.0001_initial... OK
daphne_1      |   Applying core.0002_auto_20190909_1707... OK
daphne_1      |   Applying core.0003_auto_20190912_2219... OK
daphne_1      |   Applying core.0004_archivedplaylist_created... OK
daphne_1      |   Applying core.0005_auto_20190913_1730... OK
daphne_1      |   Applying core.0006_auto_20200129_2252... OK
daphne_1      |   Applying core.0007_remove_playlistentry_song... OK
daphne_1      |   Applying core.0008_auto_20200514_1213... OK
daphne_1      |   Applying sessions.0001_initial... OK
daphne_1      |   Applying watson.0001_initial... OK
daphne_1      | Starting: bash -c DJANGO_MOCK=1 python manage.py compilescss && DJANGO_MOCK=1 python manage.py migrate --noinput && scripts/create_users.sh && /usr/local/bin/daphne --bind 0.0.0.0 --port 9000 main.asgi:application
daphne_1      | Traceback (most recent call last):
daphne_1      |   File "manage.py", line 21, in <module>
daphne_1      |     main()
daphne_1      |   File "manage.py", line 17, in main
daphne_1      |     execute_from_command_line(sys.argv)
daphne_1      |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
daphne_1      |     utility.execute()
daphne_1      |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
daphne_1      |     self.fetch_command(subcommand).run_from_argv(self.argv)
daphne_1      |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 224, in fetch_command
daphne_1      |     klass = load_command_class(app_name, subcommand)
daphne_1      |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 36, in load_command_class
daphne_1      |     module = import_module('%s.management.commands.%s' % (app_name, name))
daphne_1      |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
daphne_1      |     return _bootstrap._gcd_import(name[level:], package, level)
daphne_1      |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
daphne_1      |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
daphne_1      |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
daphne_1      |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
daphne_1      |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
daphne_1      |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
daphne_1      |   File "/usr/local/lib/python3.8/site-packages/sass_processor/management/commands/compilescss.py", line 5, in <module>
daphne_1      |     import sass
daphne_1      | ModuleNotFoundError: No module named 'sass'
daphne_1      | Operations to perform:
daphne_1      |   Apply all migrations: admin, auth, contenttypes, core, sessions, watson
daphne_1      | Running migrations:
daphne_1      |   No migrations to apply.
daphne_1      | Starting: bash -c DJANGO_MOCK=1 python manage.py compilescss && DJANGO_MOCK=1 python manage.py migrate --noinput && scripts/create_users.sh && /usr/local/bin/daphne --bind 0.0.0.0 --port 9000 main.asgi:application
daphne_1      | Traceback (most recent call last):
daphne_1      |   File "manage.py", line 21, in <module>
daphne_1      |     main()
daphne_1      |   File "manage.py", line 17, in main
daphne_1      |     execute_from_command_line(sys.argv)
daphne_1      |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
daphne_1      |     utility.execute()
daphne_1      |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
daphne_1      |     self.fetch_command(subcommand).run_from_argv(self.argv)
daphne_1      |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 224, in fetch_command
daphne_1      |     klass = load_command_class(app_name, subcommand)
daphne_1      |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 36, in load_command_class
daphne_1      |     module = import_module('%s.management.commands.%s' % (app_name, name))
daphne_1      |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
daphne_1      |     return _bootstrap._gcd_import(name[level:], package, level)
daphne_1      |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
daphne_1      |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
daphne_1      |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
daphne_1      |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
daphne_1      |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
daphne_1      |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
daphne_1      |   File "/usr/local/lib/python3.8/site-packages/sass_processor/management/commands/compilescss.py", line 5, in <module>
daphne_1      |     import sass
daphne_1      | ModuleNotFoundError: No module named 'sass'
daphne_1      | Operations to perform:
daphne_1      |   Apply all migrations: admin, auth, contenttypes, core, sessions, watson
daphne_1      | Running migrations:
daphne_1      |   No migrations to apply.
daphne_1      | Starting: bash -c DJANGO_MOCK=1 python manage.py compilescss && DJANGO_MOCK=1 python manage.py migrate --noinput && scripts/create_users.sh && /usr/local/bin/daphne --bind 0.0.0.0 --port 9000 main.asgi:application
daphne_1      | Traceback (most recent call last):
daphne_1      |   File "manage.py", line 21, in <module>
daphne_1      |     main()
daphne_1      |   File "manage.py", line 17, in main
daphne_1      |     execute_from_command_line(sys.argv)
daphne_1      |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
daphne_1      |     utility.execute()
daphne_1      |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
daphne_1      |     self.fetch_command(subcommand).run_from_argv(self.argv)
daphne_1      |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 224, in fetch_command
daphne_1      |     klass = load_command_class(app_name, subcommand)
daphne_1      |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 36, in load_command_class
daphne_1      |     module = import_module('%s.management.commands.%s' % (app_name, name))
daphne_1      |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
daphne_1      |     return _bootstrap._gcd_import(name[level:], package, level)
daphne_1      |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
daphne_1      |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
daphne_1      |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
daphne_1      |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
daphne_1      |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
daphne_1      |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
daphne_1      |   File "/usr/local/lib/python3.8/site-packages/sass_processor/management/commands/compilescss.py", line 5, in <module>
daphne_1      |     import sass
```

**Comment by raveberry** [comment]
I recently removed the sass module from the dependencies for the core application. Instead, compiled scss is now shipped with each release.
The docker-compose.yml changed in the process. If you just download the new one, everything should work again.

I forgot to mention that anywhere though. So thanks for the heads-up, I will add that to the readme.

**Comment by MickyGX** [comment]
That fixed it, only difference seems to be between old and new:

`command: bash -c "DJANGO_MOCK=1 python manage.py compilescss && DJANGO_MOCK=1 python manage.py migrate --noinput && scripts/create_users.sh && /usr/local/bin/daphne --bind 0.0.0.0 --port 9000 main.asgi:application"`

Thanks again

**Comment by raveberry** [comment]
Yes. `compilescss` was moved to the publish-stage and the other commands are now executed in the entrypoint.sh.
Great that it is working again :+1:
