### ISSUE TITLE
Error running raveberry

### ISSUE THREAD

**Issue by 1r00t** [raveberry/raveberry#91]
Hi, I just wanted to try out raveberry but I cant get it to run.
I'm using the Raspberry Pi OS on a Raspberry Pi 3 B and followed the instructions to install raveberry here.
It is my second try. I am getting the following error below when I run "raveberry run"
I was getting the same error the first time I tried but I ignored it and did a system install.
That didn't help. I was getting another error when I checked the info log. I think it was channels that threw an error about the number of arguments to init or something. Maybe I can update with that error later.
When I did the system install, I could access the webpage and play around but websockets didn't seem to work and I was getting no UI updates and had general weird behavior.
Also, I can't access the webpage with the hostname http://raveberry/. I have to use the IP.

```
pi@raspberrypi:~ $ raveberry run
first time running raveberry, preparing...
Performing Migrations
Exception in thread WSListener:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/mopidyapi/wsclient.py", line 66, in _websocket_runner
    loop.run_until_complete(packethandler())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/pi/.local/lib/python3.7/site-packages/mopidyapi/wsclient.py", line 49, in packethandler
    async with websockets.connect(self.ws_url) as ws:
  File "/home/pi/.local/lib/python3.7/site-packages/websockets/client.py", line 517, in __aenter__
    return await self
  File "/home/pi/.local/lib/python3.7/site-packages/websockets/client.py", line 535, in __await_impl__
    transport, protocol = await self._create_connection()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 968, in create_connection
    ', '.join(str(exc) for exc in exceptions)))
OSError: Multiple exceptions: [Errno 111] Connect call failed ('::1', 6680, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6680)

Operations to perform:
  Apply all migrations: admin, auth, contenttypes, core, sessions, watson
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying core.0001_initial... OK
  Applying core.0002_auto_20190909_1707... OK
  Applying core.0003_auto_20190912_2219... OK
  Applying core.0004_archivedplaylist_created... OK
  Applying core.0005_auto_20190913_1730... OK
  Applying core.0006_auto_20200129_2252... OK
  Applying core.0007_remove_playlistentry_song... OK
  Applying core.0008_auto_20200514_1213... OK
  Applying core.0009_delete_pad... OK
  Applying sessions.0001_initial... OK
  Applying watson.0001_initial... OK
Creating Users

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! Warning! Default admin password used, please consider changing it! !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

This is the basic raveberry version using a debug server.
To install with all features run `raveberry system-install`
mopidy not yet running, starting...
created secret key
linked static admin files
no song caching directory specified, using ~/Music/raveberry/
autoreload.run_with_reloader:597 INFO  Watching for file changes with StatReloader
Performing system checks...

wsclient.__init__:36 INFO  Creating Mopidy Websocket connection...
System check identified no issues (0 silenced).
November 15, 2020 - 17:03:58
Django version 2.2.17, using settings 'main.settings'
Starting ASGI/Channels version 3.0.2 development server at http://0:8080/
Quit the server with CONTROL-C.
server.run:113 INFO  HTTP/2 support not enabled (install the http2 and tls Twisted extras)
server.run:121 INFO  Configuring endpoint tcp:port=8080:interface=0
server.listen_success:155 INFO  Listening on TCP address 0.0.0.0:8080
```

**Comment by 1r00t** [comment]
After the system install I have this in my error.log

```
2020-11-15 18:05:38 server.application_checker:292 ERROR  Exception inside application: object.__init__() takes exactly one argument (the instance to initialize)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/usr/local/lib/python3.7/dist-packages/channels/sessions.py", line 254, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/usr/local/lib/python3.7/dist-packages/channels/auth.py", line 181, in __call__
    return await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/channels/routing.py", line 160, in __call__
    send,
  File "/usr/local/lib/python3.7/dist-packages/asgiref/compatibility.py", line 33, in new_application
    instance = application(scope)
  File "/usr/local/lib/python3.7/dist-packages/channels/generic/websocket.py", line 23, in __init__
    super().__init__(*args, **kwargs)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)
```

**Comment by 1r00t** [comment]
Looking at the network tab of firefox developer tools I can see that requests to /state fail with 500 Internal server error.

**Comment by raveberry** [comment]
Thanks bringing this up!
I could easily reproduce this issue. The reason is the release of django channels 3.0. Its interface was changed to account for the changes made in django 3.0. Since this project is still on version 2.2, they do not work together.
I updated the requirements to not use the new major version, new installs should not have this problem anymore.
For your system the fix would be to downgrade channels: `pip3 install -U "channels==2.2.*"`
Please let me know if this makes it work again.
