### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by Crushedice** [raveberry/raveberry#96]
Greetings.
On the PI4 i've successfully installed raveberry.
Now i wanted to give it a try on the Zero W .
Well im trying now since a few days, sometimes couldnt even install it , 
sometimes installed it with nginx error or now with a Daphne error.
I tried installing with the Raspi OS,  Ubuntu, and now with DietPi.

Most recent error log: 
```
2020-12-05 17:59:09 server.application_checker:288 ERROR  Exception inside application: catalog is missing 3 attribute(s) for relid 16600
LINE 1: ..."core_setting"."key", "core_setting"."value" FROM "core_sett...
                                                             ^
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.InternalError_: catalog is missing 3 attribute(s) for relid 16600
LINE 1: ..."core_setting"."key", "core_setting"."value" FROM "core_sett...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 100, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python3.7/dist-packages/django/urls/resolvers.py", line 536, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.7/dist-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.7/dist-packages/django/urls/resolvers.py", line 584, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.7/dist-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.7/dist-packages/django/urls/resolvers.py", line 577, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./main/urls.py", line 23, in <module>
    url(r"\/?", include("core.urls")),
  File "/usr/local/lib/python3.7/dist-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./core/urls.py", line 14, in <module>
    BASE = Base()
  File "./core/base.py", line 29, in __init__
    self.settings = Settings(self)
  File "./core/settings/settings.py", line 80, in __init__
    self.basic = Basic(base)
  File "./core/settings/basic.py", line 23, in __init__
    self.voting_system = Settings.get_setting("voting_system", "False") == "True"
  File "./core/settings/settings.py", line 48, in get_setting
    return Setting.objects.get_or_create(key=key, defaults={"value": default})[
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 538, in get_or_create
    return self.get(**kwargs), False
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.InternalError: catalog is missing 3 attribute(s) for relid 16600
LINE 1: ..."core_setting"."key", "core_setting"."value" FROM "core_sett...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.InternalError_: catalog is missing 3 attribute(s) for relid 16600
LINE 1: ..."core_setting"."key", "core_setting"."value" FROM "core_sett...
                                                             

```

edit:
I saw that the mopidy service wasnt running, and when i enter mopidy into the cmdline:

```
 mopidy

(gst-plugin-scanner:718): GStreamer-WARNING **: 17:07:49.689: Failed to load plugin '/usr/lib/arm-linux-gnueabihf/gstreamer-1.0/libgstdc1394.so': libdc1394.so.22: cannot open shared object file: No such file or directory

(gst-plugin-scanner:718): GStreamer-WARNING **: 17:07:50.292: Failed to load plugin '/usr/lib/arm-linux-gnueabihf/gstreamer-1.0/libgstchromaprint.so': libharfbuzz.so.0: cannot open shared object file: No such file or directory

(gst-plugin-scanner:718): GStreamer-WARNING **: 17:07:51.933: Failed to load plugin '/usr/lib/arm-linux-gnueabihf/gstreamer-1.0/libgstrsvg.so': libharfbuzz.so.0: cannot open shared object file: No such file or directory

(gst-plugin-scanner:718): GStreamer-WARNING **: 17:07:52.592: Failed to load plugin '/usr/lib/arm-linux-gnueabihf/gstreamer-1.0/libgstassrender.so': libharfbuzz.so.0: cannot open shared object file: No such file or directory

(gst-plugin-scanner:718): GStreamer-WARNING **: 17:07:53.185: Failed to load plugin '/usr/lib/arm-linux-gnueabihf/gstreamer-1.0/libgstttmlsubs.so': libharfbuzz.so.0: cannot open shared object file: No such file or directory
python3: girepository/cmph/cmph.c:841: cmph_search_packed: Assertion `0' failed.
Aborted

```

**Comment by raveberry** [comment]
Hm, the first error looks like the database was not migrated correctly.
Are you trying to perform a system install? Does it complete successfully or are there any errors?

**Comment by Crushedice** [comment]
On all attempts i tried to do a system-install , each on a fresh created OS . 
sometimes it seems that it completed, but with the above error . 
Sometimes it doesnt finish even . I will continue trying .
What OS do you recommend for this on a RPI Zero W ?

**Comment by raveberry** [comment]
I just installed Raveberry on a Pi Zero W and it worked. The install took a while as the device is not the most powerful one, but I received no errors. I did have a problem where nginx timed out instead of serving the request, maybe due to the same reason.
I used the newest Raspberry Pi OS Lite.
I was also able to enable streaming after installing `icecast2` and the music was played correctly. It is not the most enjoyable experience as the delays between request and response are quite noticeable, but it works. So it should be possible to install it on your device as well.

I assume your error log is from /opt/raveberry/logs/error.log? I couldn't get daphne to put its output there, it still goes directly to syslog. Can you see any related errors in `/var/log/syslog` (search for `daphne`)?

**Comment by raveberry** [comment]
Closing due to inactivity.
Feel free to reopen if the issue persists.
